AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Java Web App and MySQL Backup

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: my-codepipeline
      RoleArn: !Ref CodePipelineRole
      ArtifactStore:
        Type: S3
        Location: !Ref S3_BUCKET
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Repo: !Ref GITHUB_REPO
                Branch: !Ref GITHUB_BRANCH
                OAuthToken: !Ref GITHUB_OAUTH_TOKEN
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ClusterName: !Ref ECS_CLUSTER
                ServiceName: !Ref ECS_SERVICE
